---
# tasks file for gateway

  - name: Refresh subscription manager
    command: subscription-manager refresh 

  - name: "Setting gateway within ifcfg-{{ data[0].interface_in_name }}"
    blockinfile:
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{ data[0].interface_in_name }}"
      block: |
        GATEWAY={{ data[0].ip_out }}
        DEFROUTE=yes
        DOMAIN={{ domain_name }}.{{ domain_name_extension }}
        DNS1={{ data[2].ip }}
      insertafter: EOF
      create: yes

  - name: Install the latest of iptables-services
    ansible.builtin.yum:
      name: iptables-services
      state: latest

  - name: Flushing table
    command: "iptables -F"

  - name: Flushing tables
    command: "iptables -t {{ item }} -F"
    loop: [ nat, mangle ]

  - name: Deleting table
    command: "iptables -X"

  - name: Deleting tables
    command: "iptables -t {{ item }} -X"
    loop: [ nat, mangle ]

  - name: "Redirect web traffic to {{ data[0].interface_out_name }}"
    iptables:
      table: nat
      chain: POSTROUTING
      out_interface: "{{ data[0].interface_out_name }}"
      jump: MASQUERADE

  - name: "Redirect web traffic {{ data[0].interface_in_name }}"
    iptables:
      chain: FORWARD
      in_interface: "{{ data[0].interface_in_name }}"
      jump: ACCEPT

  - name: Setting ip forward to true
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
 
  - name: permanent ip_forward
    lineinfile:
      dest: /etc/sysctl.conf
      line: "net.ipv4.ip_forward=1"
      insertafter: EOF
      create: yes

  - name: Save current state of the firewall in system file
    community.general.iptables_state:
      state: saved
      path: /etc/sysconfig/iptables

  - name: reloading iptables.service
    service:
      name: iptables.service
      state: restarted    

  - name: reloading network
    service:
      name: network
      state: restarted

