---
# tasks file for gateway


  - name: Refresh subscription manager
    command: subscription-manager refresh 


  - name: permanent ip_forward
    lineinfile:
      dest: /hello.txt
      line: "Hello"
      insertafter: EOF
      create: yes


  - name: "Setting gateway within ifcfg-{{ gateway_interface_in_name }}"
    lineinfile:
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{ gateway_interface_in_name }}"
      block: |
        GATEWAY={{ gateway_ip_out }}
        DEFROUTE=yes
        DOMAIN={{ domainName }}
        DNS1={{ dns_ip }}
      insertafter: EOF
      create: yes




  - name: Install the latest of iptables-services
    ansible.builtin.yum:
      name: iptables-services
      state: latest



  - name: Flushing table
    command: "iptables -F"

  - name: Flushing tables
    command: "iptables -t {{ item }} -F"
    loop: [ nat, mangle ]


  - name: Deleting table
    command: "iptables -X"

  - name: Deleting tables
    command: "iptables -t {{ item }} -X"
    loop: [ nat, mangle ]


  # - name: Iptables flush nat
  #   ansible.builtin.iptables:
  #     flush: yes

  # - name: Iptables flush nat
  #   ansible.builtin.iptables:
  #     table: nat
  #     flush: yes

  # - name: Iptables flush mangle
  #   ansible.builtin.iptables:
  #     table: mangle
  #     flush: yes


  # - name: drop iptables
  #   ansible.builtin.iptables:
  #     chain: [POSTROUTING, INPUT, OUTPUT, PREROUTING, FORWARD]
  #     state: absent

  # - name: drop iptable mangle
  #   ansible.builtin.iptables:
  #     table: mangle
  #     chain: [POSTROUTING, INPUT, OUTPUT, PREROUTING, FORWARD]
  #     state: absent

  # - name: drop iptable nat
  #   ansible.builtin.iptables:
  #     table: nat
  #     chain: [POSTROUTING, INPUT, OUTPUT, PREROUTING, FORWARD]
  #     state: absent

  - name: "Redirect web traffic to {{ gateway_interface_out_name }}"
    iptables:
      table: nat
      chain: POSTROUTING
      out_interface: "{{ gateway_interface_out_name }}"
      jump: MASQUERADE

  - name: "Redirect web traffic {{ gateway_interface_in_name }}"
    iptables:
      chain: FORWARD
      in_interface: "{{ gateway_interface_in_name }}"
      jump: ACCEPT

  - name: Setting ip forward to true
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
 
  - name: permanent ip_forward
    lineinfile:
      dest: /etc/sysctl.conf
      line: "net.ipv4.ip_forward=1"
      insertafter: EOF
      create: yes


  - name: Save current state of the firewall in system file
    community.general.iptables_state:
      state: saved
      path: /etc/sysconfig/iptables

  - name: reloading iptables.service
    service:
      name: iptables.service
      state: restarted    


  - name: reloading network
    service:
      name: network
      state: restarted

